import { TnVedCode } from "../types/ved";

/**
 * Статическая база знаний: 30 кодов ТН ВЭД для популярных категорий
 * импорта из Китая на маркетплейсы (Wildberries, Ozon).
 *
 * Источники: Альта-Софт, ТКС.ру, ФТС открытые данные.
 * Ставки актуальны на февраль 2026.
 */
export const TN_VED_DATABASE: TnVedCode[] = [
  // ─── ЭЛЕКТРОНИКА ───
  {
    code: "8471300000",
    description: "Портативные компьютеры (ноутбуки) массой не более 10 кг",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011", "Нотификация ФСБ (при наличии шифрования)"],
    requiresMarking: true,
    markingCategory: "Электроника",
    keywords: ["ноутбук", "laptop", "портативный компьютер", "макбук", "macbook", "лэптоп"],
  },
  {
    code: "8517140000",
    description: "Смартфоны и телефоны для сотовых сетей",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011", "Нотификация ФСБ"],
    requiresMarking: true,
    markingCategory: "Электроника",
    keywords: ["смартфон", "телефон", "мобильный", "iphone", "айфон", "samsung", "xiaomi"],
  },
  {
    code: "8518300000",
    description: "Наушники и головные телефоны",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011"],
    requiresMarking: false,
    keywords: ["наушники", "headphones", "airpods", "эирподс", "гарнитура", "bluetooth наушники"],
  },
  {
    code: "8528720000",
    description: "Мониторы и проекторы, не содержащие телевизионного приёмника",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011"],
    requiresMarking: false,
    keywords: ["монитор", "проектор", "дисплей", "экран"],
  },
  {
    code: "8504403000",
    description: "Зарядные устройства для аккумуляторов",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011"],
    requiresMarking: false,
    keywords: ["зарядка", "зарядное устройство", "повербанк", "power bank", "блок питания", "адаптер"],
  },
  {
    code: "8473302000",
    description: "Части и принадлежности вычислительных машин (видеокарты, платы расширения)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011", "Нотификация ФСБ (шифровальные средства)"],
    requiresMarking: true,
    markingCategory: "Электроника",
    keywords: ["видеокарта", "gpu", "графическая карта", "rtx", "gtx", "radeon", "плата расширения", "материнская плата"],
  },
  {
    code: "8471490000",
    description: "Вычислительные машины прочие (десктопы, серверы, мини-ПК)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011", "Нотификация ФСБ"],
    requiresMarking: true,
    markingCategory: "Электроника",
    keywords: ["компьютер", "десктоп", "системный блок", "сервер", "мини-пк", "nuc", "pc"],
  },
  {
    code: "8471600000",
    description: "Устройства ввода/вывода (клавиатуры, мыши, сканеры, принтеры)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011"],
    requiresMarking: false,
    keywords: ["клавиатура", "мышь", "мышка", "сканер", "принтер", "keyboard", "mouse", "трекпад"],
  },
  {
    code: "8471700000",
    description: "Накопители данных (SSD, HDD, флешки)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011"],
    requiresMarking: false,
    keywords: ["ssd", "hdd", "жёсткий диск", "накопитель", "флешка", "usb-флешка", "карта памяти", "microsd"],
  },
  {
    code: "8517620000",
    description: "Маршрутизаторы, коммутаторы, точки доступа WiFi",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011", "Нотификация ФСБ"],
    requiresMarking: true,
    markingCategory: "Электроника",
    keywords: ["роутер", "маршрутизатор", "коммутатор", "свитч", "wifi", "точка доступа", "mesh"],
  },
  {
    code: "8525800000",
    description: "Телевизионные камеры, цифровые видеокамеры и видеорегистраторы",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011"],
    requiresMarking: false,
    keywords: ["видеокамера", "вебкамера", "видеорегистратор", "ip-камера", "камера наблюдения", "dashcam"],
  },
  {
    code: "8519810000",
    description: "Аудиоаппаратура (колонки, саундбары, усилители)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011"],
    requiresMarking: false,
    keywords: ["колонка", "портативная колонка", "саундбар", "усилитель", "динамик", "bluetooth колонка", "jbl"],
  },
  {
    code: "8528730000",
    description: "Телевизоры с жидкокристаллическим дисплеем (LCD/LED/OLED)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 14,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011", "Декларация ТР ТС 020/2011"],
    requiresMarking: true,
    markingCategory: "Электроника",
    keywords: ["телевизор", "tv", "smart tv", "oled", "lcd", "led телевизор"],
  },
  {
    code: "9504500000",
    description: "Игровые приставки и консоли",
    section: "XX — Разные промышленные товары",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011", "Нотификация ФСБ"],
    requiresMarking: true,
    markingCategory: "Электроника",
    keywords: ["приставка", "консоль", "playstation", "ps5", "xbox", "nintendo", "switch", "steam deck"],
  },
  {
    code: "8543709000",
    description: "Электрические машины и аппаратура прочие (умные часы, фитнес-браслеты, VR-очки)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011"],
    requiresMarking: true,
    markingCategory: "Электроника",
    keywords: ["умные часы", "смарт-часы", "фитнес-браслет", "apple watch", "vr очки", "трекер", "wearable"],
  },
  {
    code: "8443321000",
    description: "Принтеры, совмещённые с копировальным и/или факсимильным аппаратом (МФУ)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011"],
    requiresMarking: false,
    keywords: ["мфу", "принтер", "копир", "сканер-принтер", "лазерный принтер", "струйный принтер"],
  },

  // ─── ВЕНТИЛЯТОРЫ / ВОЗДУХОДУВКИ ───
  // Классификация: 2000 — если поток прямой (осевой), 4000 — если поток центробежный (радиальный).
  // Мощность (100 Вт, 200 Вт и т.д.) НЕ влияет на выбор кода — только тип крыльчатки/потока.
  {
    code: "8414592000",
    description: "Вентиляторы осевые — поток воздуха параллелен оси вращения крыльчатки (в т.ч. ручные воздуходувки Jetfan с осевой турбиной, без нагревательного элемента)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011 (НВО)", "Декларация соответствия ТР ТС 020/2011 (ЭМС)"],
    requiresMarking: false,
    riskNote: "Риск переквалификации в 8516 (бытовые электротермические приборы), если в описании или конструкции присутствует нагревательный элемент. В карточке WB/Ozon НЕЛЬЗЯ использовать слова: 'фен', 'сушка', 'нагрев', 'горячий воздух'. Используйте: 'воздуходувка', 'осевой вентилятор', 'blower'.",
    keywords: ["вентилятор осевой", "воздуходувка осевая", "турбо-фен", "фен без нагрева", "осевой вентилятор", "blower", "axial fan", "аккумуляторный вентилятор", "jetfan"],
  },
  {
    code: "8414594000",
    description: "Вентиляторы центробежные — воздух поступает по оси, выбрасывается радиально (в т.ч. ручные воздуходувки с центробежной крыльчаткой-улиткой, без нагревательного элемента)",
    section: "XVI — Машины, оборудование и механизмы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011 (НВО)", "Декларация соответствия ТР ТС 020/2011 (ЭМС)"],
    requiresMarking: false,
    riskNote: "Риск переквалификации в 8516 (бытовые электротермические приборы), если присутствует нагревательный элемент. Также возможна переквалификация в 8467 (ручной инструмент) для мощных садовых воздуходувок. В карточке НЕЛЬЗЯ: 'фен', 'сушка', 'нагрев'.",
    keywords: ["вентилятор центробежный", "воздуходувка центробежная", "центробежный нагнетатель", "улитка", "radial fan", "centrifugal blower", "садовая воздуходувка"],
  },

  // ─── ОДЕЖДА ───
  {
    code: "6109100000",
    description: "Футболки, майки и аналогичные изделия из хлопка, трикотажные",
    section: "XI — Текстильные материалы и изделия",
    dutyRate: 12,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 017/2011"],
    requiresMarking: true,
    markingCategory: "Одежда",
    keywords: ["футболка", "майка", "t-shirt", "тишка", "хлопок"],
  },
  {
    code: "6110200000",
    description: "Свитеры, пуловеры, кардиганы из хлопка, трикотажные",
    section: "XI — Текстильные материалы и изделия",
    dutyRate: 12,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 017/2011"],
    requiresMarking: true,
    markingCategory: "Одежда",
    keywords: ["свитер", "пуловер", "кардиган", "кофта", "толстовка", "худи", "hoodie"],
  },
  // ─── FASHION EXPERT MODE ───
  {
    code: "6110209100",
    description: "Худи, свитшоты с капюшоном из хлопка, трикотажные, для мужчин/мальчиков",
    section: "XI — Текстильные материалы и изделия",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 017/2011"],
    requiresMarking: true,
    markingCategory: "Одежда",
    riskNote: "Fashion Expert Mode. Классификация 61 vs 62: ключевой критерий — трикотаж (петли/футер) vs ткань (переплетение). Хлопок ≥51% → 6110 20, иначе 6110 30 (минималка 1.5 EUR/кг). Честный ЗНАК обязателен с 2021.",
    keywords: ["худи", "свитшот", "hoodie", "sweatshirt", "толстовка с капюшоном", "свитшот с капюшоном", "футер", "флис"],
  },
  {
    code: "6204620000",
    description: "Брюки женские из хлопка",
    section: "XI — Текстильные материалы и изделия",
    dutyRate: 12,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 017/2011"],
    requiresMarking: true,
    markingCategory: "Одежда",
    keywords: ["брюки", "штаны", "джинсы", "джоггеры", "легинсы", "pants", "jeans"],
  },
  {
    code: "6302600000",
    description: "Бельё столовое из хлопка (скатерти, салфетки)",
    section: "XI — Текстильные материалы и изделия",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: false,
    certTypes: [],
    requiresMarking: false,
    keywords: ["скатерть", "салфетка", "столовое бельё", "текстиль для стола"],
  },

  // ─── ОБУВЬ ───
  {
    code: "6403990000",
    description: "Обувь с верхом из натуральной кожи прочая",
    section: "XII — Обувь, головные уборы",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 017/2011"],
    requiresMarking: true,
    markingCategory: "Обувь",
    keywords: ["обувь", "кроссовки", "ботинки", "туфли", "кеды", "sneakers", "shoes"],
  },
  {
    code: "6402990000",
    description: "Обувь с верхом из пластмассы или резины прочая",
    section: "XII — Обувь, головные уборы",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 017/2011"],
    requiresMarking: true,
    markingCategory: "Обувь",
    keywords: ["резиновые сапоги", "сланцы", "шлёпки", "сандалии", "crocs", "кроксы"],
  },

  // ─── КОСМЕТИКА ───
  {
    code: "3304990000",
    description: "Средства для макияжа и ухода за кожей прочие",
    section: "VI — Продукция химической промышленности",
    dutyRate: 6.5,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Свидетельство о государственной регистрации (СГР)", "Декларация соответствия ТР ТС 009/2011"],
    requiresMarking: true,
    markingCategory: "Парфюмерия",
    keywords: ["крем", "косметика", "тональный", "помада", "тени", "макияж", "уход за кожей", "сыворотка"],
  },
  {
    code: "3305100000",
    description: "Шампуни для волос",
    section: "VI — Продукция химической промышленности",
    dutyRate: 6.5,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["СГР", "Декларация соответствия ТР ТС 009/2011"],
    requiresMarking: true,
    markingCategory: "Парфюмерия",
    keywords: ["шампунь", "бальзам", "кондиционер", "маска для волос"],
  },
  {
    code: "3303000000",
    description: "Духи и туалетная вода",
    section: "VI — Продукция химической промышленности",
    dutyRate: 6.5,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["СГР", "Декларация ТР ТС 009/2011"],
    requiresMarking: true,
    markingCategory: "Парфюмерия",
    keywords: ["духи", "парфюм", "туалетная вода", "одеколон", "perfume"],
  },

  // ─── ПРОДУКТЫ ПИТАНИЯ ───
  {
    code: "1806320000",
    description: "Шоколад и кондитерские изделия с содержанием какао, в блоках или плитках",
    section: "IV — Продукты пищевой промышленности",
    dutyRate: 7,
    vatRate: 10,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 021/2011", "Декларация ТР ТС 022/2011 (маркировка)"],
    requiresMarking: false,
    keywords: ["шоколад", "конфеты", "какао", "кондитерские изделия"],
  },
  {
    code: "0902300000",
    description: "Чай чёрный ферментированный и частично ферментированный",
    section: "II — Продукты растительного происхождения",
    dutyRate: 12.5,
    vatRate: 10,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 021/2011"],
    requiresMarking: false,
    keywords: ["чай", "чёрный чай", "пуэр", "улун", "tea"],
  },
  {
    code: "2101120000",
    description: "Готовые продукты на основе кофе",
    section: "IV — Продукты пищевой промышленности",
    dutyRate: 7.5,
    vatRate: 10,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 021/2011"],
    requiresMarking: false,
    keywords: ["кофе", "растворимый кофе", "капсулы кофе", "coffee"],
  },

  // ─── ИГРУШКИ ───
  {
    code: "9503009500",
    description: "Игрушки прочие (пластмассовые, мягкие, конструкторы)",
    section: "XX — Разные промышленные товары",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Сертификат соответствия ТР ТС 008/2011 (безопасность игрушек)"],
    requiresMarking: false,
    keywords: ["игрушка", "конструктор", "лего", "lego", "кукла", "мягкая игрушка", "пазл"],
  },

  // ─── АВТОЗАПЧАСТИ ───
  {
    code: "8708999700",
    description: "Части и принадлежности для автомобилей прочие",
    section: "XVII — Транспортные средства",
    dutyRate: 5,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Сертификат соответствия ТР ТС 018/2011"],
    requiresMarking: false,
    keywords: ["автозапчасти", "запчасти", "бампер", "фильтр", "тормозные колодки", "фара"],
  },
  {
    code: "4011100000",
    description: "Шины пневматические для легковых автомобилей",
    section: "VII — Пластмассы и каучук",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Сертификат соответствия ТР ТС 018/2011"],
    requiresMarking: true,
    markingCategory: "Шины",
    keywords: ["шины", "резина", "колёса", "покрышки", "tires"],
  },

  // ─── ДОМ И БЫТ ───
  {
    code: "9405420000",
    description: "Светильники светодиодные (LED)",
    section: "XX — Разные промышленные товары",
    dutyRate: 7.5,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 004/2011"],
    requiresMarking: false,
    keywords: ["светильник", "лампа", "LED", "люстра", "торшер", "ночник", "подсветка"],
  },
  {
    code: "3924100000",
    description: "Столовые и кухонные приборы из пластмассы",
    section: "VII — Пластмассы и каучук",
    dutyRate: 8,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 005/2011"],
    requiresMarking: false,
    keywords: ["посуда", "контейнер", "ланч-бокс", "пластиковая посуда", "тарелки"],
  },
  {
    code: "7323930000",
    description: "Столовые и кухонные приборы из нержавеющей стали",
    section: "XV — Недрагоценные металлы",
    dutyRate: 12,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 005/2011"],
    requiresMarking: false,
    keywords: ["кастрюля", "сковорода", "нержавейка", "столовые приборы", "вок", "термос"],
  },

  // ─── СУМКИ ───
  {
    code: "4202120000",
    description: "Чемоданы и сумки дорожные с лицевой поверхностью из пластмассы или текстиля",
    section: "VIII — Кожевенное сырьё, кожа и изделия",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: false,
    certTypes: [],
    requiresMarking: false,
    keywords: ["чемодан", "сумка", "рюкзак", "портфель", "дорожная сумка", "backpack"],
  },
  {
    code: "4202210000",
    description: "Сумки с лицевой поверхностью из натуральной кожи",
    section: "VIII — Кожевенное сырьё, кожа и изделия",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: false,
    certTypes: [],
    requiresMarking: false,
    keywords: ["кожаная сумка", "клатч", "кошелёк", "портмоне"],
  },

  // ─── СПОРТ ───
  {
    code: "9506910000",
    description: "Снаряды и оборудование для фитнеса",
    section: "XX — Разные промышленные товары",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: false,
    certTypes: [],
    requiresMarking: false,
    keywords: ["гантели", "фитнес", "тренажёр", "коврик", "йога", "эспандер", "гиря"],
  },

  // ─── ФОТО/КАМЕРЫ ───
  {
    code: "9006530000",
    description: "Фотокамеры для плёнки шириной 35 мм",
    section: "XVIII — Оптические приборы",
    dutyRate: 0,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 020/2011"],
    requiresMarking: true,
    markingCategory: "Фотоаппараты",
    keywords: ["фотоаппарат", "камера", "фотокамера", "gopro", "экшн-камера"],
  },

  // ─── МЕБЕЛЬ ───
  {
    code: "9403600000",
    description: "Мебель деревянная прочая (столы, полки, стеллажи)",
    section: "XX — Разные промышленные товары",
    dutyRate: 12,
    vatRate: 20,
    excise: 0,
    requiresCertification: false,
    certTypes: [],
    requiresMarking: false,
    keywords: ["стол", "полка", "стеллаж", "комод", "тумба", "мебель"],
  },

  // ─── БИЖУТЕРИЯ ───
  {
    code: "7117190000",
    description: "Бижутерия из недрагоценных металлов прочая",
    section: "XV — Недрагоценные металлы",
    dutyRate: 15,
    vatRate: 20,
    excise: 0,
    requiresCertification: false,
    certTypes: [],
    requiresMarking: false,
    keywords: ["бижутерия", "браслет", "кольцо", "серьги", "цепочка", "ожерелье", "украшения"],
  },

  // ─── КАНЦЕЛЯРИЯ / ШКОЛА ───
  {
    code: "4202320000",
    description: "Пеналы, футляры, чехлы с лицевой поверхностью из текстиля (в т.ч. полиэстер, нейлон, хлопок)",
    section: "VIII — Кожевенное сырьё, кожа и изделия",
    dutyRate: 10,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Сертификат соответствия ТР ТС 007/2011 (безопасность детской продукции)", "Протокол испытаний (фталаты, формальдегид, миграция красителей)"],
    requiresMarking: false,
    riskNote: "Если позиционируется для детей до 14 лет — обязателен СЕРТИФИКАТ (не декларация!). ТР ТС 007/2011 — протокол испытаний в аккредитованной лаборатории. Стоимость ~15-30K руб, срок 2-4 недели.",
    keywords: ["пенал", "пенал школьный", "пенал текстильный", "пенал тканевый", "футляр для ручек", "pencil case", "косметичка детская"],
  },
  {
    code: "3926909700",
    description: "Пеналы, футляры, коробки из пластмасс (EVA, полипропилен, ПВХ)",
    section: "VII — Пластмассы и каучук",
    dutyRate: 6.5,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Сертификат соответствия ТР ТС 007/2011 (безопасность детской продукции)", "Протокол испытаний (фталаты, свинец, миграция)"],
    requiresMarking: false,
    riskNote: "Детская продукция — повышенный контроль ФТС. EVA-кейсы могут переквалифицировать в 4202 (чемоданы/сумки), если есть текстильная подкладка. В карточке WB указывать 'пенал пластиковый', не 'косметичка'.",
    keywords: ["пенал пластиковый", "пенал EVA", "пенал жёсткий", "кейс для канцелярии", "pencil box", "пенал-книжка"],
  },

  // ─── ДЕТСКИЕ ТОВАРЫ ───
  {
    code: "9401710000",
    description: "Сиденья (стулья, кресла) с мягкой обивкой, с металлическим каркасом",
    section: "XX — Разные промышленные товары",
    dutyRate: 12,
    vatRate: 20,
    excise: 0,
    requiresCertification: true,
    certTypes: ["Декларация соответствия ТР ТС 025/2012 (мебельная продукция)"],
    requiresMarking: false,
    keywords: ["стул", "кресло", "офисное кресло", "барный стул", "табурет"],
  },
];

/**
 * Минимальные ценовые пороги ФТС (профили риска) — USD за единицу.
 * Если инвойс ниже порога — автоматическая КТС (корректировка таможенной стоимости).
 */
export const FTS_PRICE_THRESHOLDS: Record<string, number> = {
  "8471300000": 200,  // ноутбуки — мин $200
  "8517140000": 50,   // смартфоны — мин $50
  "8518300000": 5,    // наушники — мин $5
  "6109100000": 2,    // футболки — мин $2
  "6110200000": 4,    // свитеры — мин $4
  "6110209100": 4,    // худи/свитшоты мужские хлопок — мин $4
  "6403990000": 10,   // обувь кожа — мин $10
  "6402990000": 3,    // обувь пластик — мин $3
  "3304990000": 1,    // косметика — мин $1
  "9503009500": 1,    // игрушки — мин $1
  "4011100000": 15,   // шины — мин $15
  "4202120000": 3,    // сумки — мин $3
  "8473302000": 100,  // видеокарты — мин $100
  "8471490000": 150,  // десктопы/серверы — мин $150
  "8471600000": 3,    // клавиатуры/мыши — мин $3
  "8471700000": 10,   // SSD/HDD — мин $10
  "8517620000": 10,   // роутеры — мин $10
  "8525800000": 15,   // видеокамеры — мин $15
  "8528730000": 50,   // телевизоры — мин $50
  "9504500000": 100,  // игровые консоли — мин $100
  "8543709000": 20,   // умные часы — мин $20
  "8443321000": 30,   // МФУ/принтеры — мин $30
  "8414592000": 5,    // вентиляторы осевые — мин $5
  "8414594000": 5,    // вентиляторы центробежные — мин $5
  "4202320000": 0.5,  // пеналы текстильные — мин $0.50
  "3926909700": 0.3,  // пеналы пластиковые — мин $0.30
};

/**
 * Категории обязательной маркировки Честный ЗНАК (актуально на февраль 2026).
 */
export const MARKING_CATEGORIES = [
  "Табачная продукция",
  "Обувь",
  "Лекарственные препараты",
  "Парфюмерия",
  "Шины",
  "Одежда",
  "Фотоаппараты",
  "Молочная продукция",
  "Упакованная вода",
  "Пиво и слабоалкогольные напитки",
  "Электроника",
  "БАДы",
  "Антисептики",
  "Велосипеды",
];
